import type { PortfolioAsset, FavoriteMovie, AboutBio } from "./supabase";

export const DEFAULT_PORTFOLIO_ASSETS: PortfolioAsset[] = [
  // APPS
  {
    id: "app-1",
    type: "app",
    title: "AnonRoom",
    description: "Ephemeral, encrypted anonymous chat rooms with real-time presence, custom room codes, and zero log storage. Built with React, Supabase & WebSockets.",
    url: "https://anonroom.vanshkumar.in",
    image_url: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80",
    favicon_url: null,
    sort_order: 1,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "app-2",
    type: "app",
    title: "JeeFlow",
    description: "Comprehensive study tracker, mock test performance analyzer, and countdown timer tailored for JEE 2026 aspirants.",
    url: "https://jeeflow.vanshkumar.in",
    image_url: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=600&q=80",
    favicon_url: null,
    sort_order: 2,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "app-3",
    type: "app",
    title: "Bollywood Movie Quiz",
    description: "Interactive Hindi cinema word-guessing game with dynamic hints, letter tracking, solo puzzles, and live real-time multiplayer room battles.",
    url: "/games/bollywood",
    image_url: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=600&q=80",
    favicon_url: null,
    sort_order: 3,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "app-4",
    type: "app",
    title: "Portfolio OS",
    description: "Personal interactive hub featuring synthesized Web Audio sound engine, Cmd+K command palette, music player, and mini-games.",
    url: "https://github.com/DROPTASK/Mydetails",
    image_url: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=600&q=80",
    favicon_url: null,
    sort_order: 4,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // INTERESTS
  {
    id: "interest-1",
    type: "interest",
    title: "Competitive Programming & Problem Solving",
    description: "Exploring algorithmic paradigms, dynamic programming, graph traversal, and mathematical proofs on Codeforces and LeetCode.",
    url: null,
    image_url: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=600&q=80",
    favicon_url: null,
    sort_order: 1,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "interest-2",
    type: "interest",
    title: "Physics & Theoretical Mechanics",
    description: "Deep dive into kinematics, rotational dynamics, electromagnetism, and calculus as part of Arjuna JEE 2.0 curriculum.",
    url: null,
    image_url: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=600&q=80",
    favicon_url: null,
    sort_order: 2,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "interest-3",
    type: "interest",
    title: "Modern Web Systems & Real-time Sync",
    description: "Building resilient client-server apps with TypeScript, React 18, WebSockets, Supabase Postgres changes, and Tailwind CSS.",
    url: null,
    image_url: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=600&q=80",
    favicon_url: null,
    sort_order: 3,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "interest-4",
    type: "interest",
    title: "Sound Synthesis & Late-Night Beats",
    description: "Synthesizing soft tones with Web Audio API oscillators, relaxing lo-fi soundtracks, and Bollywood film scores.",
    url: null,
    image_url: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=600&q=80",
    favicon_url: null,
    sort_order: 4,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // LINKS
  {
    id: "link-1",
    type: "link",
    title: "GitHub Profile",
    description: "Explore all open-source repositories, utilities, and daily code commits.",
    url: "https://github.com/vansh-kumar",
    image_url: null,
    favicon_url: null,
    sort_order: 1,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "link-2",
    type: "link",
    title: "AnonRoom Project",
    description: "Launch the ephemeral anonymous chat application.",
    url: "https://anonroom.vanshkumar.in",
    image_url: null,
    favicon_url: null,
    sort_order: 2,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "link-3",
    type: "link",
    title: "JeeFlow Planner",
    description: "Exam countdown, topic checklists, and mock revision tracker.",
    url: "https://jeeflow.vanshkumar.in",
    image_url: null,
    favicon_url: null,
    sort_order: 3,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "link-4",
    type: "link",
    title: "Email & Direct Inquiries",
    description: "Send an email for inquiries, collaborations, or tech discussions.",
    url: "mailto:vanshadd003@gmail.com",
    image_url: null,
    favicon_url: null,
    sort_order: 4,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "link-5",
    type: "link",
    title: "Live Chat Guestbook",
    description: "Leave a message directly on this portfolio or chat with the AI assistant.",
    url: "/chat",
    image_url: null,
    favicon_url: null,
    sort_order: 5,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // PHOTOS
  {
    id: "photo-1",
    type: "photo",
    title: "Workspace & Code Aesthetics",
    description: "Focus space setup with dual monitors, mechanical keyboard, and evening lighting.",
    url: null,
    image_url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80",
    favicon_url: null,
    sort_order: 1,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "photo-2",
    type: "photo",
    title: "Mechanical Keyboard & Focus",
    description: "Tactile switches tuned for late-night programming sessions and problem-solving.",
    url: null,
    image_url: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80",
    favicon_url: null,
    sort_order: 2,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "photo-3",
    type: "photo",
    title: "Physics & Problem Solving Notes",
    description: "Calculus derivations, mechanics diagrams, and revision formulas.",
    url: null,
    image_url: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=800&q=80",
    favicon_url: null,
    sort_order: 3,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "photo-4",
    type: "photo",
    title: "Late Night Coding Glow",
    description: "Terminal windows, compiler outputs, and dark mode IDE theme.",
    url: null,
    image_url: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80",
    favicon_url: null,
    sort_order: 4,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "photo-5",
    type: "photo",
    title: "Books & Competitive Prep",
    description: "HC Verma, Irodov, and reference texts on the study shelf.",
    url: null,
    image_url: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&w=800&q=80",
    favicon_url: null,
    sort_order: 5,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "photo-6",
    type: "photo",
    title: "Minimalist Desk Flow",
    description: "Clean workspace keeping distractions minimal during deep study blocks.",
    url: null,
    image_url: "https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?auto=format&fit=crop&w=800&q=80",
    favicon_url: null,
    sort_order: 6,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },

  // GAMES
  {
    id: "game-1",
    type: "game",
    title: "Minecraft",
    description: "Sandbox survival, redstone engineering, and endless algorithmic creativity.",
    url: "https://www.minecraft.net",
    image_url: "https://images.unsplash.com/photo-1627856013091-fed6e4e30025?auto=format&fit=crop&w=600&q=80",
    favicon_url: null,
    sort_order: 1,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "game-2",
    type: "game",
    title: "Portal 2",
    description: "Masterpiece of spatial puzzle mechanics, physics, and dark humor.",
    url: "https://store.steampowered.com/app/620/Portal_2/",
    image_url: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80",
    favicon_url: null,
    sort_order: 2,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "game-3",
    type: "game",
    title: "Chess.com",
    description: "Rapid and blitz tactical matches, solving daily positional puzzles.",
    url: "https://www.chess.com",
    image_url: "https://images.unsplash.com/photo-1529699211952-734e80c4d42b?auto=format&fit=crop&w=600&q=80",
    favicon_url: null,
    sort_order: 3,
    is_published: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEFAULT_FAVORITE_MOVIES: FavoriteMovie[] = [
  {
    id: "fav-1",
    tmdb_id: 101,
    title: "3 Idiots",
    poster_path: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=400&q=80",
    backdrop_path: "https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=1280&q=80",
    overview: "Two friends search for their long lost companion who inspired them to think differently at engineering college.",
    release_date: "2009-12-25",
    vote_average: 8.4,
    sort_order: 1,
    created_at: new Date().toISOString(),
  },
  {
    id: "fav-2",
    tmdb_id: 157336,
    title: "Interstellar",
    poster_path: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    overview: "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel.",
    release_date: "2014-11-05",
    vote_average: 8.4,
    sort_order: 2,
    created_at: new Date().toISOString(),
  },
  {
    id: "fav-3",
    tmdb_id: 102,
    title: "Dangal",
    poster_path: "https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=400&q=80",
    backdrop_path: "https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=1280&q=80",
    overview: "Former wrestler Mahavir Singh Phogat trains his daughters Geeta and Babita to become world-class wrestlers.",
    release_date: "2016-12-23",
    vote_average: 8.2,
    sort_order: 3,
    created_at: new Date().toISOString(),
  },
  {
    id: "fav-4",
    tmdb_id: 27205,
    title: "Inception",
    poster_path: "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    backdrop_path: "https://image.tmdb.org/t/p/w1280/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    overview: "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets, is offered a chance to regain his old life.",
    release_date: "2010-07-15",
    vote_average: 8.4,
    sort_order: 4,
    created_at: new Date().toISOString(),
  },
];

export const DEFAULT_ABOUT_BIO: AboutBio = {
  title: "Hey, I'm Vansh Kumar.",
  subtitle: "Class 11 Computer Science • JEE 2026 Aspirant",
  description: "I'm a high-school developer and student based in Meerut, India. When I'm not balancing physics equations and calculus problems for JEE preparation, I architect clean web products with React, TypeScript, and Supabase.",
  location: "Meerut, UP, India",
  curriculum: "Arjuna JEE 2.0",
  stack: "TS, React, Python",
  status_title: "Class 11 CS • Arjuna JEE 2.0",
  status_subtitle: "Building AnonRoom & JeeFlow",
};
